# Generated by Django 6.0.1 on 2026-01-22 09:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='newspaper',
            name='unique_lower_title_content',
        ),
        migrations.AddConstraint(
            model_name='newspaper',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_lower_title'),
        ),
    ]
