# Generated by Django 6.0.1 on 2026-01-22 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_remove_newspaper_unique_lower_title_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
