# Generated by Django 6.0.1 on 2026-01-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ('published_date',)},
        ),
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ('username',), 'verbose_name': 'redactors'},
        ),
    ]
