# Generated by Django 6.0.1 on 2026-01-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_newspaper_options_alter_redactor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ('username',), 'verbose_name': 'redactor'},
        ),
    ]
