# Generated by Django 6.0.1 on 2026-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveConstraint(
            model_name='newspaper',
            name='unique_lower_title',
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
